on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.8'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      
      - name: Run automated tests
        run: flutter test
